# Generated by Django 5.2.14 on 2026-06-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_staff_only', models.BooleanField(default=False)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='programs.program')),
            ],
            options={
                'verbose_name': 'réalisation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InternalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_staff_only', models.BooleanField(default=False, verbose_name='Réservé au staff')),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='programs.program')),
            ],
            options={
                'verbose_name': 'actualité',
                'verbose_name_plural': 'actualités',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_staff_only', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='programs.program')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
