# Generated by Django 5.2.14 on 2026-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('widget_type', models.CharField(choices=[('kpi', 'Indicateur clé'), ('chart', 'Graphique (placeholder)'), ('list', 'Liste'), ('text', 'Texte')], default='kpi', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'widget tableau de bord',
                'ordering': ['order'],
            },
        ),
    ]
