# Generated by Django 5.2.14 on 2026-06-01 14:43

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('institutional', 'Institutionnel'), ('report', 'Rapport synthétique'), ('policy', 'Politique / procédure'), ('other', 'Autre')], default='institutional', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.public_upload_path)),
                ('private_file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.private_upload_path)),
                ('is_published', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False, verbose_name='Fichier privé (staff)')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='programs.program')),
            ],
            options={
                'verbose_name': 'document',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
