# Generated by Django 5.2.14 on 2026-06-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Description')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Secteur')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Zone')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'programme',
                'verbose_name_plural': 'programmes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('value', models.CharField(max_length=100, verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('period', models.CharField(blank=True, max_length=80, verbose_name='Période')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible publiquement')),
                ('is_featured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='programs.program')),
            ],
            options={
                'verbose_name': 'indicateur',
                'ordering': ['-is_featured', 'label'],
            },
        ),
    ]
